import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import './globals.css'

import { AppHeader } from './components'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <div className='flex justify-start items-stretch h-screen w-full'>
          <aside className='hidden lg:flex lg:flex-none lg:justify-center lg:items-start lg:w-[72px] lg:h-screen lg:bg-[#B6B7C3] lg:pt-4'>
            <div className='w-[35px] h-[35px] rounded-full bg-[#001458]' />
          </aside>
          <div className='w-full overflow-y-auto'>
            <AppHeader />
            <div className='container mx-auto'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  )
}
