import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import './globals.css'

import { AppHeader } from './components'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <AppHeader />
        <div className='container mx-auto'>{children}</div>
      </body>
    </html>
  )
}
